export const rankings = [
  {
    fecha: "13 de Mayo de 2020",
    municipios: [
      {
        nombre: "Monterrey",
        sitio: false,
        insumos: false,
        tablas: false,
        entregados: false,
        utilizados: false,
        donativos: false,
        informacion: false,
        proxima: false,
        urls: [""],
      },
      {
        nombre: "Guadalupe",
        sitio: true,
        insumos: true,
        tablas: true,
        entregados: true,
        utilizados: true,
        donativos: false,
        informacion: true,
        proxima: false,
        urls: [
          "http://www.guadalupe.gob.mx/apoyoscovid/",
          "http://www.guadalupe.gob.mx/coronavirus/",
          "http://www.guadalupe.gob.mx/transparencia-covid-19/",
        ],
      },
      {
        nombre: "San Nicolás",
        sitio: true,
        insumos: true,
        tablas: true,
        entregados: true,
        utilizados: true,
        donativos: true,
        informacion: true,
        proxima: true,
        urls: [
          "https://www.sanicolas.gob.mx/gastoscovid/",
          "https://www.sanicolas.gob.mx/category/noticias/",
        ],
        documentos: [
          "https://www.sanicolas.gob.mx/wp-content/uploads/2020/05/TRANSPARENCIA-DONATIVOS-COVID-19.xlsx",
        ],
      },
      {
        nombre: "Apodaca",
        sitio: true,
        insumos: true,
        tablas: true,
        entregados: false,
        utilizados: false,
        donativos: true,
        informacion: true,
        proxima: false,
        urls: [
          "http://coronavirus.apodaca.gob.mx/",
          "http://coronavirus.apodaca.gob.mx/rendicion-de-cuentas/",
        ],
        documentos: [
          "http://coronavirus.apodaca.gob.mx/wp-content/uploads/2020/05/COVID-19-COTAI-Marzo-ABRIL-2020-1.xls",
        ],
      },
      {
        nombre: "Escobedo",
        sitio: true,
        insumos: true,
        tablas: true,
        entregados: true,
        utilizados: true,
        donativos: true,
        informacion: true,
        proxima: true,
        urls: [
          "https://escobedo.gob.mx/?p=proactiva",          
          "https://escobedo.gob.mx/?p=interes",
          "https://escobedo.gob.mx/?p=covid",
        ],
        documentos: [
          "https://escobedo.gob.mx/transparencia/proactiva/docs/COVID19_GASTO.xlsx",
        ],
      },
      {
        nombre: "Sta. Catarina",
        sitio: true,
        insumos: true,
        tablas: true,
        entregados: true,
        utilizados: true,
        donativos: true,
        informacion: true,
        proxima: false,
        urls: ["http://www.stacatarina.gob.mx/apps/covid19/"],
        documentos: [
          "http://www.stacatarina.gob.mx/apps/covid19/files/pagos.xlsx",
        ],
      },
      {
        nombre: "Juarez",
        sitio: false,
        insumos: true,
        tablas: true,
        entregados: false,
        utilizados: false,
        donativos: false,
        informacion: false,
        proxima: false,
        urls: ["http://juarez-nl.gob.mx/transparencia/"],
      },
      {
        nombre: "García",
        sitio: false,
        insumos: true,
        tablas: true,
        entregados: false,
        utilizados: true,
        donativos: true,
        informacion: true,
        proxima: false,
        urls: ["http://trans.garcia.gob.mx/index.php"],
        documentos: [
          "https://docs.google.com/spreadsheets/d/1s1PzL9vesAA355P5_WXHPcXgkOi-7APZletL99sSz4I/edit#gid=585561491",
        ],
      },
      {
        nombre: "San Pedro",
        sitio: true,
        insumos: true,
        tablas: true,
        entregados: true,
        utilizados: true,
        donativos: true,
        informacion: true,
        proxima: true,
        urls: [
          "https://sanpedro.gob.mx/coronavirus/#compras",
          "https://airtable.com/shrql5Lsg3UP3Omj6/tbldIlMdgQxw4mLiL/viwPRNsMphcQyEtl7?backgroundColor=gray&blocks=hide",
        ],
      },
      {
        nombre: "Estado de Nuevo León",
        sitio: true,
        insumos: true,
        tablas: false,
        entregados: false,
        utilizados: false,
        donativos: false,
        informacion: true,
        proxima: false,
        urls: [
          "http://www.nl.gob.mx/coronavirus",
          "http://www.nl.gob.mx/informefinanciero-covid-19",
          "http://www.nl.gob.mx/series/acciones-de-apoyo-las-familias-de-nuevo-leon-ante-covid-19",
        ],
      }
    ],
  },
  {
    fecha: "9 de Mayo de 2020",
    municipios: [
      {
        nombre: "Monterrey",
        sitio: false,
        insumos: false,
        tablas: false,
        entregados: false,
        utilizados: false,
        donativos: false,
        informacion: false,
        proxima: false,
        urls: [""],
      },
      {
        nombre: "Guadalupe",
        sitio: 1,
        insumos: false,
        tablas: false,
        entregados: true,
        utilizados: true,
        donativos: false,
        informacion: false,
        proxima: false,
        urls: [
          "http://www.guadalupe.gob.mx/apoyoscovid/",
          "http://www.guadalupe.gob.mx/coronavirus/",
        ],
      },
      {
        nombre: "San Nicolás",
        sitio: false,
        insumos: true,
        tablas: true,
        entregados: true,
        utilizados: true,
        donativos: false,
        informacion: true,
        proxima: true,
        urls: [
          "https://www.sanicolas.gob.mx/gastoscovid/",
          "https://www.sanicolas.gob.mx/category/noticias/",
        ],
      },
      {
        nombre: "Apodaca",
        sitio: true,
        insumos: false,
        tablas: false,
        entregados: false,
        utilizados: false,
        donativos: false,
        informacion: false,
        proxima: false,
        urls: ["http://coronavirus.apodaca.gob.mx/"],
      },
      {
        nombre: "Escobedo",
        sitio: true,
        insumos: true,
        tablas: true,
        entregados: true,
        utilizados: true,
        donativos: true,
        informacion: true,
        proxima: true,
        urls: [
          "https://escobedo.gob.mx/?p=proactiva",
          "https://escobedo.gob.mx/transparencia/proactiva/docs/COVID19_GASTO.xlsx",
          "https://escobedo.gob.mx/?p=covid",
        ],
      },
      {
        nombre: "Sta. Catarina",
        sitio: true,
        insumos: false,
        tablas: false,
        entregados: true,
        utilizados: true,
        donativos: true,
        informacion: true,
        proxima: false,
        urls: [
          "http://www.stacatarina.gob.mx/apps/covid19/",
          "http://www.stacatarina.gob.mx/apps/covid19/files/pagos.xlsx",
        ],
      },
      {
        nombre: "Juarez",
        sitio: false,
        insumos: false,
        tablas: false,
        entregados: false,
        utilizados: false,
        donativos: false,
        informacion: false,
        proxima: false,
        urls: [""],
      },
      {
        nombre: "García",
        sitio: false,
        insumos: false,
        tablas: false,
        entregados: false,
        utilizados: false,
        donativos: false,
        informacion: false,
        proxima: false,
        urls: [""],
      },
      {
        nombre: "San Pedro",
        sitio: true,
        insumos: true,
        tablas: true,
        entregados: true,
        utilizados: true,
        donativos: true,
        informacion: true,
        proxima: true,
        urls: ["https://sanpedro.gob.mx/coronavirus/"],
      },
      {
        nombre: "Estado de Nuevo León",
        sitio: true,
        insumos: true,
        tablas: false,
        entregados: false,
        utilizados: false,
        donativos: false,
        informacion: true,
        proxima: false,
        urls: [
          "http://www.nl.gob.mx/coronavirus",
          "http://www.nl.gob.mx/informefinanciero-covid-19",
          "http://www.nl.gob.mx/series/acciones-de-apoyo-las-familias-de-nuevo-leon-ante-covid-19",
        ],
      },
    ],
  },
];

export const score = [
  {
    fecha: "13 de Mayo de 2020",
    municipios: [
      {
        nombre: "Escobedo",
        calificacion: 100,
      },
      {
        nombre: "San Pedro",
        calificacion: 100,
      },
      {
        nombre: "San Nicolas",
        calificacion: 100,
      },
      {
        nombre: "Santa Catarina",
        calificacion: 91,
      },
      {
        nombre: "Guadalupe",
        calificacion: 75,
      },
      {
        nombre: "Apodaca",
        calificacion: 58,
      },
      {
        nombre: "García",
        calificacion: 58,
      },
      {
        nombre: "Estado de NL",
        calificacion: 33,
      },
      {
        nombre: "Juárez",
        calificacion: 17,
      },
      {
        nombre: "Monterrey",
        calificacion: 0,
      },
    ]
  },
  {
    fecha: "9 de Mayo de 2020",
    municipios: [
      {
        nombre: "Escobedo",
        calificacion: 100,
      },
      {
        nombre: "San Pedro",
        calificacion: 100,
      },
      {
        nombre: "Santa Catarina",
        calificacion: 75,
      },
      {
        nombre: "San Nicolas",
        calificacion: 66,
      },
      {
        nombre: "Guadalupe",
        calificacion: 50,
      },
      {
        nombre: "Estado de NL",
        calificacion: 33,
      },
      {
        nombre: "Apodaca",
        calificacion: 17,
      },
      {
        nombre: "García",
        calificacion: 0,
      },
      {
        nombre: "Juárez",
        calificacion: 0,
      },
      {
        nombre: "Monterrey",
        calificacion: 0,
      },
    ],
  },
];

export const conceptos = [
  {
    nombre: "Micrositio",
    slug: "sitio",
  },
  {
    nombre: "Adquisición de Insumos",
    slug: "insumos",
  },
  {
    nombre: "Tablas en Excel o Software Libre",
    slug: "tablas",
  },
  {
    nombre: "Apoyos Entregados",
    slug: "entregados",
  },
  {
    nombre: "Apoyos Utilizados",
    slug: "utilizados",
  },
  {
    nombre: "Donativos Particulares",
    slug: "donativos",
  },
  {
    nombre: "Fecha de última actualización",
    slug: "informacion",
  },
  {
    nombre: "Fecha de próxima actualización",
    slug: "proxima",
  },
];
